import {
  ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Bell, Bookmark, BookOpen, Brush, Calendar, Camera,
  Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Circle, Clock, Cloud,
  Code2, Copy, Download, Droplet, Eye, File, FileCode2, Folder, FolderCode, FolderOpen, Globe2,
  Heart, Home, Image, Info, KeyRound, Laptop, Lightbulb, Link, List, Lock, Mail, MapPin, Menu,
  MessageCircle, Mic, Minus, Moon, MoreHorizontal, Music, Palette, Paperclip, Pencil, Pin, Play, Plus,
  Rocket, Search, Settings, Shield, Smile, Snowflake, Sparkles, Square, Star, Sun, Terminal,
  AtSign, Clock3, GitPullRequest, Grid2X2, SquarePen, ThumbsUp, Trash2, User, Users, Video, WandSparkles, X, Zap,
  type LucideIcon
} from 'lucide-react'

export const builtinIcons: Record<string, LucideIcon> = {
  music: Music,
  sparkles: Sparkles,
  'wand-sparkles': WandSparkles,
  image: Image,
  send: ArrowUp,
  'folder-code': FolderCode,
  'square-pen': SquarePen,
  'git-pull-request': GitPullRequest,
  'grid-2x2': Grid2X2,
  'clock-3': Clock3,
  'at-sign': AtSign,
  heart: Heart,
  droplet: Droplet,
  star: Star,
  snowflake: Snowflake,
  pin: Pin,
  home: Home,
  search: Search,
  settings: Settings,
  menu: Menu,
  plus: Plus,
  minus: Minus,
  check: Check,
  'check-circle': CheckCircle2,
  close: X,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  circle: Circle,
  square: Square,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  zap: Zap,
  'book-open': BookOpen,
  bookmark: Bookmark,
  bell: Bell,
  calendar: Calendar,
  clock: Clock,
  user: User,
  users: Users,
  'message-circle': MessageCircle,
  mail: Mail,
  globe: Globe2,
  laptop: Laptop,
  folder: Folder,
  'folder-open': FolderOpen,
  file: File,
  'file-code': FileCode2,
  code: Code2,
  terminal: Terminal,
  copy: Copy,
  download: Download,
  external: Link,
  link: Link,
  paperclip: Paperclip,
  pencil: Pencil,
  brush: Brush,
  palette: Palette,
  camera: Camera,
  video: Video,
  mic: Mic,
  play: Play,
  rocket: Rocket,
  lightbulb: Lightbulb,
  shield: Shield,
  lock: Lock,
  key: KeyRound,
  eye: Eye,
  info: Info,
  list: List,
  'more-horizontal': MoreHorizontal,
  'map-pin': MapPin,
  smile: Smile,
  'thumbs-up': ThumbsUp,
  trash: Trash2
}

export const builtinIconLabels: Readonly<Record<string, string>> = Object.freeze({
  music: '音乐', sparkles: '闪烁', 'wand-sparkles': '魔法闪烁', image: '图片', send: '发送', 'folder-code': '代码文件夹',
  'square-pen': '新建任务', 'git-pull-request': '拉取请求', 'grid-2x2': '站点', 'clock-3': '已安排', 'at-sign': '插件',
  heart: '爱心', droplet: '水滴', star: '星星', snowflake: '雪花', pin: '图钉', home: '首页', search: '搜索', settings: '设置',
  menu: '菜单', plus: '加号', minus: '减号', check: '勾选', 'check-circle': '完成', close: '关闭', 'arrow-up': '向上箭头',
  'arrow-down': '向下箭头', 'arrow-left': '向左箭头', 'arrow-right': '向右箭头', 'chevron-up': '向上折叠', 'chevron-down': '向下展开',
  'chevron-left': '向左切换', 'chevron-right': '向右切换', circle: '圆形', square: '方形', sun: '太阳', moon: '月亮', cloud: '云朵',
  zap: '闪电', 'book-open': '打开的书', bookmark: '书签', bell: '铃铛', calendar: '日历', clock: '时钟', user: '用户', users: '用户组',
  'message-circle': '对话', mail: '邮件', globe: '地球', laptop: '电脑', folder: '文件夹', 'folder-open': '打开的文件夹', file: '文件',
  'file-code': '代码文件', code: '代码', terminal: '终端', copy: '复制', download: '下载', external: '外链', link: '链接', paperclip: '附件',
  pencil: '铅笔', brush: '画笔', palette: '调色板', camera: '相机', video: '视频', mic: '麦克风', play: '播放', rocket: '火箭',
  lightbulb: '灵感', shield: '盾牌', lock: '锁定', key: '钥匙', eye: '查看', info: '信息', list: '列表', 'more-horizontal': '更多',
  'map-pin': '地图定位', smile: '笑脸', 'thumbs-up': '点赞', trash: '删除'
})

export const builtinIconOptions = Object.keys(builtinIcons)
