import {
  ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Bell, Bookmark, BookOpen, Brush, Calendar, Camera,
  Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Circle, Clock, Cloud,
  Code2, Copy, Download, Droplet, Eye, File, FileCode2, Folder, FolderCode, FolderOpen, Globe2,
  Heart, Home, Image, Info, KeyRound, Laptop, Lightbulb, Link, List, Lock, Mail, MapPin, Menu,
  MessageCircle, Mic, Minus, Moon, MoreHorizontal, Music, Palette, Paperclip, Pencil, Pin, Play, Plus,
  Rocket, Search, Settings, Shield, Smile, Snowflake, Sparkles, Square, Star, Sun, Terminal,
  AtSign, Clock3, GitPullRequest, Grid2X2, SquarePen, ThumbsUp, Trash2, User, Users, Video, WandSparkles, X, Zap,
  type LucideIcon
} from 'lucide-react'

export const builtinIcons: Record<string, LucideIcon> = {
  music: Music,
  sparkles: Sparkles,
  'wand-sparkles': WandSparkles,
  image: Image,
  send: ArrowUp,
  'folder-code': FolderCode,
  'square-pen': SquarePen,
  'git-pull-request': GitPullRequest,
  'grid-2x2': Grid2X2,
  'clock-3': Clock3,
  'at-sign': AtSign,
  heart: Heart,
  droplet: Droplet,
  star: Star,
  snowflake: Snowflake,
  pin: Pin,
  home: Home,
  search: Search,
  settings: Settings,
  menu: Menu,
  plus: Plus,
  minus: Minus,
  check: Check,
  'check-circle': CheckCircle2,
  close: X,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  circle: Circle,
  square: Square,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  zap: Zap,
  'book-open': BookOpen,
  bookmark: Bookmark,
  bell: Bell,
  calendar: Calendar,
  clock: Clock,
  user: User,
  users: Users,
  'message-circle': MessageCircle,
  mail: Mail,
  globe: Globe2,
  laptop: Laptop,
  folder: Folder,
  'folder-open': FolderOpen,
  file: File,
  'file-code': FileCode2,
  code: Code2,
  terminal: Terminal,
  copy: Copy,
  download: Download,
  external: Link,
  link: Link,
  paperclip: Paperclip,
  pencil: Pencil,
  brush: Brush,
  palette: Palette,
  camera: Camera,
  video: Video,
  mic: Mic,
  play: Play,
  rocket: Rocket,
  lightbulb: Lightbulb,
  shield: Shield,
  lock: Lock,
  key: KeyRound,
  eye: Eye,
  info: Info,
  list: List,
  'more-horizontal': MoreHorizontal,
  'map-pin': MapPin,
  smile: Smile,
  'thumbs-up': ThumbsUp,
  trash: Trash2
}
