const glyphs: Record<string, string> = {
  music: '♫',
  sparkles: '✦',
  'wand-sparkles': '✧',
  image: '▣',
  send: '↑',
  'folder-code': '⌘',
  heart: '♥',
  droplet: '●',
  star: '★',
  snowflake: '❄',
  pin: '●',
  home: '⌂',
  search: '⌕',
  settings: '⚙',
  menu: '☰',
  plus: '+',
  minus: '−',
  check: '✓',
  'check-circle': '◉',
  close: '×',
  'arrow-up': '↑',
  'arrow-down': '↓',
  'arrow-left': '←',
  'arrow-right': '→',
  'chevron-up': '⌃',
  'chevron-down': '⌄',
  'chevron-left': '‹',
  'chevron-right': '›',
  circle: '○',
  square: '□',
  sun: '☀',
  moon: '☾',
  cloud: '☁',
  zap: 'ϟ',
  'book-open': '▤',
  bookmark: '▮',
  bell: '♧',
  calendar: '▦',
  clock: '◷',
  user: '♙',
  users: '♙',
  'message-circle': '◌',
  mail: '✉',
  globe: '◎',
  laptop: '▱',
  folder: '□',
  'folder-open': '▱',
  file: '▤',
  'file-code': '⌘',
  code: '</>',
  terminal: '▻_',
  copy: '▣',
  download: '↓',
  external: '↗',
  link: '∞',
  paperclip: '⌕',
  pencil: '✎',
  brush: '✧',
  palette: '◉',
  camera: '▣',
  video: '▶',
  mic: '♩',
  play: '▶',
  rocket: '➤',
  lightbulb: '☼',
  shield: '⬟',
  lock: '▣',
  key: '⚿',
  eye: '◉',
  info: 'ⓘ',
  list: '☷',
  'more-horizontal': '•••',
  'map-pin': '●',
  smile: '☺',
  'thumbs-up': '♥',
  trash: '⌫'
}

export const BUILTIN_ICON_GLYPHS: Readonly<Record<string, string>> = Object.freeze(glyphs)

export function resolveBuiltinIconGlyph(name: string, fallback = BUILTIN_ICON_GLYPHS.sparkles ?? '✦'): string {
  return BUILTIN_ICON_GLYPHS[name] ?? fallback
}
